spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect #tells Hibernate how to generate SQL optimized for PostgreSQL.

  mail:
    host: localhost
    port: 1025
    username: mahmoud
    password: mahmoud
    properties:
      mail:
        smtp:
          trust:
        auth: true
        starttls:
          enable: true
          require: true
        connectiontimout: 5000
        timeout: 3000
        writetimeout: 5000
